name: Preview Teardown

on:
  pull_request_target:
    types: [closed]

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  preview-teardown:
    runs-on: ubuntu-latest
    steps:
    - name: Install Surge
      run: npm install surge

    - name: Teardown surge preview
      id: deploy
      run: npx surge teardown https://quarkusguru-${{ github.event.number }}-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      - name: Update PR status comment
        uses: actions-cool/maintain-one-comment@v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🙈 The PR is closed and the preview is expired.
            <!-- Sticky Pull Request Comment -->
          body-include: '<!-- Sticky Pull Request Comment -->'
          number: ${{ github.event.number }}